name: Trigger auto deployment for pestest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pestest-AutoDeployTrigger-6bae991c-6ec7-4080-82b2-bcb405594310.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.PESTEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        run: |
          docker login athul.azurecr.io -u ${{ secrets.PESTEST_REGISTRY_USERNAME }} -p ${{ secrets.PESTEST_REGISTRY_PASSWORD }}
          docker build \
            --build-arg VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }} \
            --build-arg VITE_TENANT_ID=${{ secrets.VITE_TENANT_ID }} \
            -t athul.azurecr.io/pestest:${{ github.sha }} .
          docker push athul.azurecr.io/pestest:${{ github.sha }}

      - name: Deploy to Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: pestest
          resourceGroup: zapia
          registryUrl: athul.azurecr.io
          registryUsername: ${{ secrets.PESTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PESTEST_REGISTRY_PASSWORD }}
          imageToDeploy: athul.azurecr.io/pestest:${{ github.sha }}
          environmentVariables: |
            AGENT_NAME=${{ secrets.AGENT_NAME }}
            AZURE_ENDPOINT=${{ secrets.AZURE_ENDPOINT }}
            AGENT_VERSION=${{ secrets.AGENT_VERSION }}
          
            

     

